"""Add code_verifier column to users table

Revision ID: b20acc597995
Revises: c1f3e8647134
Create Date: 2025-06-15 23:24:16.414275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20acc597995'
down_revision: Union[str, None] = 'c1f3e8647134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('code_verifier', sa.Text(), nullable=True))
    op.create_index('idx_user_id', 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_user_id', table_name='users')
    op.drop_column('users', 'code_verifier')
    # ### end Alembic commands ###
